
var qcardDeck = [
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",
	"You go to Jupiter to get more stupider. _ go to Mars to get more candy bars.",
	"Area 51 guards use this to stop the raiders.",
	"What will you bring to raid Area 51?",
	"What will always get you laid?",
	"Why am I sticky?",
	"A recent laboratory study shows that undergraduates have 50% less sex after being exposed to _.",
	"Fun tip! When your man asks you to go down on him, try surprising him with _ instead.",
	"What are my parents hiding from me?",
	"In L.A. County Jail, word is you can trade 200 cigarettes for _.",
	"What did I bring back from Mexico?",
	"What don't you want to find in your Kung Pao chicken.",
	"What will I bring back in time to convince people that I am a powerful wizard?",
	"How am I maintaining my relationship status?",
	"_. It's a trap!",
	"Coming to Broadway this season, _: The Musical.",
	"While the United States races the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",
	"After the earthquake, Sean Penn brought _ to the people of Haiti.",
	"Next on ESPN2, the World Series of _.",
	"But before I kill you, Mr. Bond, I must show you _.",
	"What gives me uncontrollable gas?",
	"The new Chevy Tahoe. With the power and space to take _ everywhere you go.",
	"The class field trip was completely ruined by _.",
	"What's my secret power?",
	"What would grandma find disturbing, yet oddly charming?",
	"What did the U.S. airdrop to the children of Afghanistan?",
	"What helps Obama unwind?",
	"What did Vin Diesel eat for dinner?",
	"_: good to the last drop.",
	"What gets better with age?",
	"_: kid-tested, mother-approved.",
	"Daddy, why is mommy crying?",
	"What's Teach for America using to inspire inner city students to succeed?",
	"Life for American Indians was forever changed when the White Man introduced them to _.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
	"Why do I hurt all over?",
	"What am I giving up for Lent?",
	"What's George W. Bush thinking about right now?",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.",
	"When I am President of the United States, I will create the Department of _.",
	"When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",
	"What's my anti-drug.",
	"What never fails to liven up the party?",
	"What's the new fad diet?",
	"Fortnite bad. _ good.",
	"No, you're _!",
	"Hey r/all! Check out _!",
	"Why I can't sleep at night.",
	"What's that smell.",
	"I got 99 problems but _ ain't one.",
	"Maybe she's born with it. Maybe it's _.",
	"What's the next happy meal toy.",
	"Here's the church, here's the steeple, open the doors, and there is _.",
	"It's a pity kids these days are all getting involved with _.",
	"Today on Maury: \"Help! My son is _\".",
	"Alternative medicine is now embracing the curative powers of _.",
	"What's that sound?",
	"What ended my last relationship.",
	"MTV's new reality show features eight washed up celebrities living with _.",
	"I drink to forget _.",
	"I'm sorry professor. I couldn't complete my homework because _.",
	"What's Batman's guilty pleasure?",
	"This is the way the world ends... This is the way the worlds ends... Not with a bang with but with a _.",
	"What's a girl's best friend?",
	"TSA guidelines now prohibit _ on airplanes.",
	"_. That's how I want to die.",
	"In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
	"I get by with a little help from _.",
	"Dear Abby, I'm having some trouble with _ and would like your advice.",
	"Instead of coal, Santa now gives the bad children _.",
	"What's the most emo?",
	"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
	"A romantic candlelit dinner would be incomplete without _.",
	"_. Betcha can't have just one.",
	"White people like _.",
	"_. High five, bro.",
	"Next from J.K. Rowling: Harry Potter and the Chamber of _.",
	"Introducing Xtreme Baseball! It's like baseball, but with _!",
	"War! What is it good for?",
  "How did I lose my virginity?",
  "During sex, I like to think about _."
];

var qcardDeckSFS = [
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",
	"You go to Jupiter to get more stupider. _ go to Mars to get more candy bars.",
	"Area 51 guards use this to stop the raiders.",
	"What will you bring to raid Area 51?",
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",


	"What are my parents hiding from me?",
	"In L.A. County Jail, word is you can trade 200 cigarettes for _.",
	"What did I bring back from Mexico?",
	"What don't you want to find in your Kung Pao chicken.",
	"What will I bring back in time to convince people that I am a powerful wizard?",
	"How am I maintaining my relationship status?",
	"_. It's a trap!",
	"Coming to Broadway this season, _: The Musical.",
	"While the United States races the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",
	"After the earthquake, Sean Penn brought _ to the people of Haiti.",
	"Next on ESPN2, the World Series of _.",
	"But before I kill you, Mr. Bond, I must show you _.",
	"What gives me uncontrollable gas?",
	"The new Chevy Tahoe. With the power and space to take _ everywhere you go.",
	"The class field trip was completely ruined by _.",
	"What's my secret power?",
	"What would grandma find disturbing, yet oddly charming?",
	"What did the U.S. airdrop to the children of Afghanistan?",
	"What helps Obama unwind?",
	"What did Vin Diesel eat for dinner?",
	"_: good to the last drop.",
	"What gets better with age?",
	"_: kid-tested, mother-approved.",
	"Daddy, why is mommy crying?",
	"What's Teach for America using to inspire inner city students to succeed?",
	"Life for American Indians was forever changed when the White Man introduced them to _.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
	"Why do I hurt all over?",
	"What am I giving up for Lent?",
	"What's George W. Bush thinking about right now?",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.",
	"When I am President of the United States, I will create the Department of _.",
	"When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",
	"What's my anti-drug.",
	"What never fails to liven up the party?",
	"What's the new fad diet?",
	"Fortnite bad. _ good.",
	"No, you're _!",
	"Hey r/all! Check out _!",
	"Why I can't sleep at night.",
	"What's that smell.",
	"I got 99 problems but _ ain't one.",
	"Maybe she's born with it. Maybe it's _.",
	"What's the next happy meal toy.",
	"Here's the church, here's the steeple, open the doors, and there is _.",
	"It's a pity kids these days are all getting involved with _.",
	"Today on Maury: \"Help! My son is _\".",
	"Alternative medicine is now embracing the curative powers of _.",
	"What's that sound?",
	"What ended my last relationship.",
	"MTV's new reality show features eight washed up celebrities living with _.",
	"I drink to forget _.",
	"I'm sorry professor. I couldn't complete my homework because _.",
	"What's Batman's guilty pleasure?",
	"This is the way the world ends... This is the way the worlds ends... Not with a bang with but with a _.",
	"What's a girl's best friend?",
	"TSA guidelines now prohibit _ on airplanes.",
	"_. That's how I want to die.",
	"In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
	"I get by with a little help from _.",
	"Dear Abby, I'm having some trouble with _ and would like your advice.",
	"Instead of coal, Santa now gives the bad children _.",
	"What's the most emo?",
	"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
	"A romantic candlelit dinner would be incomplete without _.",
	"_. Betcha can't have just one.",
	"White people like _.",
	"_. High five, bro.",
	"Next from J.K. Rowling: Harry Potter and the Chamber of _.",
	"Introducing Xtreme Baseball! It's like baseball, but with _!",
	"War! What is it good for?"
];


var qcardCID;
var pack = "traditional";

module.exports = {
    getCardById: function(cid) {
        if (cid < 0) return "";
        if (pack == "traditional") return qcardDeck[cid];
        else if (pack=="traditional-sfs") return qcardDeckSFS[cid];
    },
    initQCard: function(p) {
        pack = p;
        qcardCID = [];
        var a = 0;
        switch (pack) {
            case "traditional":
                a = qcardDeck.length;
                break;
            case "traditional-sfs":
                a = qcardDeckSFS.length;
                break;
        }

        for (var i = 0; i < a; i++) {
            qcardCID[i] = i;
        }
        qcardCID.sort(function () {
            return Math.random() - 0.5;
        });
    },
    getRandomCID: function() {
        if (qcardCID.length <=0) {
            this.initQCard(pack);
        }
        return qcardCID.pop();
    }
};
