
var qcardDeck = [
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",
	"You go to Jupiter to get more stupider. _ go to Mars to get more candy bars.",
	"Area 51 guards use this to stop the raiders.",
	"What will you bring to raid Area 51?",
	"What will always get you laid?",
	"Why am I sticky?",
	"A recent laboratory study shows that undergraduates have 50% less sex after being exposed to _.",
	"Fun tip! When your man asks you to go down on him, try surprising him with _ instead.",
	"What are my parents hiding from me?",
	"In L.A. County Jail, word is you can trade 200 cigarettes for _.",
	"What did I bring back from Mexico?",
	"What don't you want to find in your Kung Pao chicken.",
	"What will I bring back in time to convince people that I am a powerful wizard?",
	"How am I maintaining my relationship status?",
	"_. It's a trap!",
	"Coming to Broadway this season, _: The Musical.",
	"While the United States races the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",
	"After the earthquake, Sean Penn brought _ to the people of Haiti.",
	"Next on ESPN2, the World Series of _.",
	"But before I kill you, Mr. Bond, I must show you _.",
	"What gives me uncontrollable gas?",
	"The new Chevy Tahoe. With the power and space to take _ everywhere you go.",
	"The class field trip was completely ruined by _.",
	"What's my secret power?",
	"What would grandma find disturbing, yet oddly charming?",
	"What did the U.S. airdrop to the children of Afghanistan?",
	"What helps Obama unwind?",
	"What did Vin Diesel eat for dinner?",
	"_: good to the last drop.",
	"What gets better with age?",
	"_: kid-tested, mother-approved.",
	"Daddy, why is mommy crying?",
	"What's Teach for America using to inspire inner city students to succeed?",
	"Life for American Indians was forever changed when the White Man introduced them to _.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
	"Why do I hurt all over?",
	"What am I giving up for Lent?",
	"What's George W. Bush thinking about right now?",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.",
	"When I am President of the United States, I will create the Department of _.",
	"When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",
	"What's my anti-drug.",
	"What never fails to liven up the party?",
	"What's the new fad diet?",
	"Fortnite bad. _ good.",
	"No, you're _!",
	"Hey r/all! Check out _!",
	"Why I can't sleep at night.",
	"What's that smell.",
	"I got 99 problems but _ ain't one.",
	"Maybe she's born with it. Maybe it's _.",
	"What's the next happy meal toy.",
	"Here's the church, here's the steeple, open the doors, and there is _.",
	"It's a pity kids these days are all getting involved with _.",
	"Today on Maury: \"Help! My son is _\".",
	"Alternative medicine is now embracing the curative powers of _.",
	"What's that sound?",
	"What ended my last relationship.",
	"MTV's new reality show features eight washed up celebrities living with _.",
	"I drink to forget _.",
	"I'm sorry professor. I couldn't complete my homework because _.",
	"What's Batman's guilty pleasure?",
	"This is the way the world ends... This is the way the worlds ends... Not with a bang with but with a _.",
	"What's a girl's best friend?",
	"TSA guidelines now prohibit _ on airplanes.",
	"_. That's how I want to die.",
	"In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
	"I get by with a little help from _.",
	"Dear Abby, I'm having some trouble with _ and would like your advice.",
	"Instead of coal, Santa now gives the bad children _.",
	"What's the most emo?",
	"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
	"A romantic candlelit dinner would be incomplete without _.",
	"_. Betcha can't have just one.",
	"White people like _.",
	"_. High five, bro.",
	"Next from J.K. Rowling: Harry Potter and the Chamber of _.",
	"Introducing Xtreme Baseball! It's like baseball, but with _!",
	"War! What is it good for?",
  "How did I lose my virginity?",
  "During sex, I like to think about _."
];

var qcardDeckSFS = [
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",
	"You go to Jupiter to get more stupider. _ go to Mars to get more candy bars.",
	"Area 51 guards use this to stop the raiders.",
	"What will you bring to raid Area 51?",
	"Take me home... _.",
	"Why my computer does not work.",
	"Guess who? It's _!",
	"What's that on the couch...?",
	"I'm sorry I didn't hear you, I had _ in my mouth.",
	"Guns don't kill people, _ kill people.",
	"I need to see _ more often.",
	"_! Never gets old!",
	"Children should see _ more.",
	"I like my _ fresh.",
	"I eat _ fresh",
	"Back in the old days we had _.",
	"Instead of paying expensive college tution, I spend my money on _.",
	"It's 12 o'clock! Time for _ to appear!",
	"I saw _ last night at your house...",
	"That sucks! Try _!",
	"What gets me high?",
	"New _ dropped! Check it out!",
	"What can fit inside my mouth?",
	"_. I want to take this home with me.",
	"Balanced, as _ should be.",
	"Ha! You look like _.",


	"What are my parents hiding from me?",
	"In L.A. County Jail, word is you can trade 200 cigarettes for _.",
	"What did I bring back from Mexico?",
	"What don't you want to find in your Kung Pao chicken.",
	"What will I bring back in time to convince people that I am a powerful wizard?",
	"How am I maintaining my relationship status?",
	"_. It's a trap!",
	"Coming to Broadway this season, _: The Musical.",
	"While the United States races the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.",
	"After the earthquake, Sean Penn brought _ to the people of Haiti.",
	"Next on ESPN2, the World Series of _.",
	"But before I kill you, Mr. Bond, I must show you _.",
	"What gives me uncontrollable gas?",
	"The new Chevy Tahoe. With the power and space to take _ everywhere you go.",
	"The class field trip was completely ruined by _.",
	"What's my secret power?",
	"What would grandma find disturbing, yet oddly charming?",
	"What did the U.S. airdrop to the children of Afghanistan?",
	"What helps Obama unwind?",
	"What did Vin Diesel eat for dinner?",
	"_: good to the last drop.",
	"What gets better with age?",
	"_: kid-tested, mother-approved.",
	"Daddy, why is mommy crying?",
	"What's Teach for America using to inspire inner city students to succeed?",
	"Life for American Indians was forever changed when the White Man introduced them to _.",
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with _.",
	"Why do I hurt all over?",
	"What am I giving up for Lent?",
	"What's George W. Bush thinking about right now?",
	"The Smithsonian Museum of Natural History has just opened an interactive exhibit on _.",
	"When I am President of the United States, I will create the Department of _.",
	"When I am a billionaire, I shall erect a 50-foot statue to commemorate _.",
	"What's my anti-drug.",
	"What never fails to liven up the party?",
	"What's the new fad diet?",
	"Fortnite bad. _ good.",
	"No, you're _!",
	"Hey r/all! Check out _!",
	"Why I can't sleep at night.",
	"What's that smell.",
	"I got 99 problems but _ ain't one.",
	"Maybe she's born with it. Maybe it's _.",
	"What's the next happy meal toy.",
	"Here's the church, here's the steeple, open the doors, and there is _.",
	"It's a pity kids these days are all getting involved with _.",
	"Today on Maury: \"Help! My son is _\".",
	"Alternative medicine is now embracing the curative powers of _.",
	"What's that sound?",
	"What ended my last relationship.",
	"MTV's new reality show features eight washed up celebrities living with _.",
	"I drink to forget _.",
	"I'm sorry professor. I couldn't complete my homework because _.",
	"What's Batman's guilty pleasure?",
	"This is the way the world ends... This is the way the worlds ends... Not with a bang with but with a _.",
	"What's a girl's best friend?",
	"TSA guidelines now prohibit _ on airplanes.",
	"_. That's how I want to die.",
	"In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.",
	"I get by with a little help from _.",
	"Dear Abby, I'm having some trouble with _ and would like your advice.",
	"Instead of coal, Santa now gives the bad children _.",
	"What's the most emo?",
	"In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?",
	"A romantic candlelit dinner would be incomplete without _.",
	"_. Betcha can't have just one.",
	"White people like _.",
	"_. High five, bro.",
	"Next from J.K. Rowling: Harry Potter and the Chamber of _.",
	"Introducing Xtreme Baseball! It's like baseball, but with _!",
	"War! What is it good for?"
];

var qAsainDeck = [
	"My parents stop me from _ with the opposite sex.",
	"My white friends think that _ is sushi.",
	"My brain can fit so many _ in it.",
	"Cuffing season is overrated. All you need is _.",
	"Me: I'm so single, Also me: *_*.",
	"My parents encouraged _ in the household.",
	"I get rid of my dignity before I try _.",
	"When you recall the time you _, you're overwhelmed with joy.",
	"Your parents love to talk about their riveting experience in _.",
	"Cashier: Sorry, we ran out of boba. Friend: Just get _, it's the same anyways.",
	"When my mum sees _, she thinks I should be like that.",
	"You know you're at an Asian party when there is _.",
	"_ is a simple trick I use to win arguments.",
	"I'm not safe unless I carry _ in my wallet.",
	"I only  use _ in my own country.",
	"K-Dramas are just female _.",
	"Bringing _ to your family gatherings is always a good idea.",
	"The biggest challenge for asian immigrants is _.",
  "Ever since the start of subtle asian dating, I have experienced difficulty in _.",
	"In my family, we don't _ with each other.",
	"_ helps to speak a foreign language better.",
	"My going out makeup look is _.",
	"My number one turn-on is _.",
	"I refuse that _ is good for me.",
	"Trying to find the perfect _ ratio is almost impossible.",
	"According to a Japanese legend, you can't sleep at night because _ is haunting you.",
	"_ is better than East Meets East and Tinder.",
	"I would throw away my boba if there's _ in it.",
	"Nothing makes my parents happier than _.",
	"I was taught to run away from _.",
	"My mum could spend hours in a local supermarket to fine the best _.",
	"My biggest difficulty in dating is _.",
	"My new year resolution is to _.",
	"Shooting your shot on subtle asian dating by _.",
	"A meal is not complete without _.",
	"Hiding _ from your parents is quite difficult.",
	"I would walk 5 blocks below zero degrees to get _.",
	"Being a white washed asian means I like _.",
	"My parents roast me for _.",
	"I'm polite on the outside but _ on the inside.",
	"I was told that _ could clear my acne.",
	"I don't think my parents know that I like _.",
	"\"_ would make you smarter.\" - my dad.",
	"_ means she/he is 200% into me.",
	"I'm studying _ so you know I'd be making that $$$ in the future.",
	"Wholesome fuccbois: I'm here for a _ time, not a long time.",
	"When I'm feeling down, I try _.",
	"I'm attracted to fuckboys because _.",
	"When you fail a test, you _.",
	"I can survive on _ if I'm on a desert island.",
	"The one class I'm failing in is _.",
	"Whenever I visit my relatives, my parents would remind me to _.",
	"A constructive advice to get my life together would be _.",
	"I will work for _ for free.",
	"See a therapist: $100/hour. _: free.",
	"My white teacher thought me and my classmates are related because we have _.",
	"Instead of asking the girl/guy out, I prefer _.",
	"Me: I'm a bad bitch. Also me: *_*.",
	"Mixing _ with vodka makes the best pregame.",
	"Anxiety is just another term for _.",
	"She's not angry. She just wants _.",
	"I'm the only person in my friend group who is _.",
	"If you don't send _ with flowers to ABGs, do you really have game?",
	"When relatives ask why you're single, you defend yourself by _.",
	"My dad thinks _ means I'm gay.",
	"My parents think I'm studying when I'm actully _.",
	"Doctor: Do you do extreme sports? Me: Yea, sometimes I _.",
	"I will have you know that I graduated top of my class in _.",
	"\"Remember to bring _ before you leave the house\" -my mum.",
	"Unpopular opinion: _ will be dead pretty soon.",
	"There are only three ways to motivate people: money, fear, and _.",
	"When there is _, my mum thinks it's time to study.",
	"Every asian kitchen has _.",
	"I only date people who are _.",
	"When my parents hear logical arguments, they think it's _.",
	"My parents and I have _ in common.",
	"_ in a 100% effective birth control.",
	"Wholesome fuccbois only want _ and it's disgusting.",
	"I broke up with an ABG by saying \"you can find someone else to buy you boba and _ from now on.\"",
	"I use _ to hide all my life problems.",
	"Guys who watch anime have the best _.",
	"I could tell the difference between Chinese, Korean, and Japanese by the way they _.",
	"I was shook when I found out my white friend eats _.",
	"Sharing my _ experince on subtle asian pages is a new therapy.",
	"I look too young to be _.",
	"Rather than studying and saving my GPA, I prefer _.",
	"\"You are a _ to the family.\" - every asian parent ever.",
	"My grandparents think K-pop is really just _.",
	"_ is not a personality trait.",
	"At every family gathering, your relatives would talk about _.",
	"I spend all my money on _ and complain about being broke.",
	"You're not an ABG if you don't _.",
	"My grandma is really traditional but she would still try _.",
	"_ at 3am is very dangerous.",
	"_ is a subtle asian student trait.",
	"Sometimes I'm grateful for my _.",
	"_ means I'm becoming a gangster, according to my mom.",
	"My parents go crazy when they see _.",
	"My mum thinks _ equals failure."
];

var qcardCID;
var pack = "traditional";

module.exports = {
    getCardById: function(cid) {
        if (cid < 0) return "";
        if (pack == "traditional") return qcardDeck[cid];
        else if (pack=="traditional-sfs") return qcardDeckSFS[cid];
				else if (pack="asain") return qAsainDeck[cid];
    },
    initQCard: function(p) {
        pack = p;
        qcardCID = [];
        var a = 0;
        switch (pack) {
            case "traditional":
                a = qcardDeck.length;
                break;
            case "traditional-sfs":
                a = qcardDeckSFS.length;
                break;
						case "asain":
								a = qAsainDeck.length;
								break;
        }

        for (var i = 0; i < a; i++) {
            qcardCID[i] = i;
        }
        qcardCID.sort(function () {
            return Math.random() - 0.5;
        });
    },
    getRandomCID: function() {
        if (qcardCID.length <=0) {
            this.initQCard(pack);
        }
        return qcardCID.pop();
    }
};
